### ISSUE TITLE
TASK Create a HTTP client library for Facebook

### ISSUE THREAD

**Issue by thejhh** [hyperifyio/io.hyperify.core#14]
### Goal

Create an HTTP client library for the Facebook Graph API to enable automated posting to Facebook pages. This library will simplify direct HTTP requests for our development team. The focus is on Enabling automated posts to Facebook pages.

The library will integrate with our services, emphasizing security and ease of use. Developing this library in-house allows for greater control over security and customization. The decision to maintain our own library is based on [proof of concept work](https://github.com/sendanor/project-sendanor.fi/issues/164) showing that internal maintenance in this case is more efficient than using external libraries.

### Complete sequence diagram

```mermaid
sequenceDiagram

    box Frontend
        participant Alice
        participant Browser
        participant CLI
    end

    box Green The Goal
        participant Library
    end

    box Backend
        participant GraphAPI
    end

    Alice->>CLI: Start login

    CLI->>Library: Get authentication URL with these permissions
    Library-->>CLI: Here's https://www.facebook.com/dialog/oauth

    CLI-->>Alice: Go to https://www.facebook.com/dialog/oauth

    Alice->>Browser: Opens up https://www.facebook.com/dialog/oauth
    Alice-->>Browser: Follows up on instructions to authenticate
    Browser-->>Alice: All ready, you can close the window

    Library-->>CLI: All set! Here's code.

    CLI->>Library: Here's my code, give me user access token

    Library->>GraphAPI: Here's my code, give me user access token
    GraphAPI-->>Library: Here's user access token

    Library-->>CLI: Here's user access token

    CLI->>Library: Here's user access token, give me list of pages with page access tokens

    Library->>GraphAPI: Here's my user access token, give me list of pages with accounts (pages) with access tokens
    GraphAPI-->>Library: Here's list of accounts (pages)
    Library-->>CLI: Here's list of accounts (pages) with access tokens

    CLI-->>Alice: Here's the page access token

    Alice->>CLI: Here's the page access token, post on my feed.

    CLI->>Library: Here's page access token, post on this feed
    Library->>GraphAPI: Here's page access token, post on this feed.
    GraphAPI-->>Library: Posted!
    Library-->>CLI: Posted!

    CLI-->>Alice: Post ready!

```

### Subtasks

* [x] User Access Token DTO
* [x] Accounts DTO
* [x] DTO for response from posting to a feed
* [x] Basic client service
* [x] End point to fetch user access token: GET https://graph.facebook.com/v19.0/oauth/access_token
* [x] End point to fetch pages with page access tokens: GET https://graph.facebook.com/v19.0/me/accounts
* [x] End point for posting on a feed (page): POST https://graph.facebook.com/v19.0/me/feed
* [x] Fetch URL to initiate authentication process, eg. https://www.facebook.com/dialog/oauth
